# Is debug mode enabled
debug = true
# Database source, to sqlite, it is a file
db-address = "web.db"
# HTTP listen address
listen-address = ":1111"
# Is using nginx reverse proxy, header key : X-real-ip
nginx-proxy = false
# Site title
site-title = "mysite"
# Home title
home-title = "hello, this is my site"
# Banner image and text
banner-image = "../images/banner_top.jpg"
banner-text = "Hello world"
# Footer copyright info
footer-copyright = "2016-2017 gocode.cc"
# About html file can render in about page
about-html-file = 'about.html'
# Timezone
timezone = "Asia/Shanghai"
# Weibo address, if set, it will be displayed in the footer
weibo-address = ""
# Github address, if set, it will be displayed in the footer
github-address = ""
# Comment provider, now supports duoshuo(unavailable), livere, 163, native
comment-provider = ""
# Support alipay or wxpay donate
call-secret = ""
donate-call = ""
[cdn]
bootstrap-css = "http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css"
bootstrap-theme-css = "http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap-theme.min.css"
bootstrap-js = "http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"
jquery-js = "http://apps.bdimg.com/libs/jquery/1.11.3/jquery.min.js"
jquery-placeholder-js = "https://cdn.bootcss.com/jquery-placeholder/2.0.7/jquery.placeholder.min.js"
font-awesome-css = "http://apps.bdimg.com/libs/fontawesome/4.4.0/css/font-awesome.min.css"
[msg-push]
host = ""
sc-key = ""
# Comment context
[comment-context]
# If comment is livere, data_uid field must be set
data_uid = ""
# If comment is 163, productKey and loader must be set
productKey = ""
loader = ""