# Is debug mode enabled
debug = false
# Database source, to sqlite, it is a file
db-address = "web.db"
# HTTP listen address
listen-address = ":1111"
# Is using nginx reverse proxy, header key : X-real-ip
nginx-proxy = false
# Site title
site-title = "mysite"
# Home title
home-title = "hello, this is my site"
# Banner image and text
banner-image = "../images/banner_top.jpg"
banner-text = "Hello world"
# Footer copyright info
footer-copyright = "2016-2017 gocode.cc"
# About html file can render in about page
about-html-file = 'about.html'
# Timezone
timezone = "Asia/Shanghai"
# Weibo address, if set, it will be displayed in the footer
weibo-address = ""
# Github address, if set, it will be displayed in the footer
github-address = ""
# Comment provider, now supports duoshuo(unavailable), livere, 163, native
comment-provider = ""
# Support alipay donate
call-secret = "123"
donate-call = "http://localhost:8100"
# Comment context
[comment-context]
# If comment is livere, data_uid field must be set
data_uid = ""
# If comment is 163, productKey and loader must be set
productKey = ""
loader = ""